model_train_type = "sdxl-lora"
pretrained_model_name_or_path = "/root/autodl-fs/illustriousXL10_v10.safetensors"
train_data_dir = "/root/autodl-tmp/rocket"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = false
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64
output_name = "rocket"
output_dir = "/root/autodl-fs/rocket"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 1
max_train_epochs = 50
train_batch_size = 2
gradient_checkpointing = false
gradient_accumulation_steps = 1
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 1
unet_lr = 1
text_encoder_lr = 1
lr_scheduler = "constant"
lr_warmup_steps = 0
optimizer_type = "Prodigy"
network_module = "networks.lora"
network_dim = 32
network_alpha = 16
network_dropout = 0.01
sample_prompts = "r0cket raccoon,(masterpiece, best quality:1.2), 1boy, solo,furry,furry male, --n lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry,  --w 1024 --h 1024  --l 7  --s 24  --d 1337"
sample_sampler = "euler_a"
sample_every_n_epochs = 1
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 1
max_token_length = 255
multires_noise_iterations = 6
multires_noise_discount = 0.3
color_aug = false
flip_aug = false
random_crop = false
seed = 1337
mixed_precision = "bf16"
full_bf16 = true
xformers = true
sdpa = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
persistent_data_loader_workers = true
optimizer_args = [
  "decouple=True",
  "weight_decay=0.01",
  "use_bias_correction=True",
  "d_coef=2.0"
]
